export const products = [
  {
    id: 1,
    img: require("./images/productOne.jpg"),
    title: "Classic Cola",
    desc: "Refreshing cola with a rich flavor.",
    price: 20,
    rate: 4.5,
  },
  {
    id: 2,
    img: require("./images/product2.jpg"),
    title: "Orange Juice",
    desc: "Freshly squeezed amazing orange juice.",
    price: 25,
    rate: 4.2,
  },
  {
    id: 3,
    img: require("./images/product3.jpg"),
    title: "Lemonade",
    desc: "Crisp and tangy cold lemonade wow.",
    price: 18,
    rate: 4.0,
  },
  {
    id: 4,
    img: require("./images/product4.jpg"),
    title: "Iced Tea",
    desc: "Chilled tea with a hot hint of lemon.",
    price: 22,
    rate: 3.9,
  },
  {
    id: 5,
    img: require("./images/product5.jpg"),
    title: "Mango Smoothie",
    desc: "Creamy mango smoothie with real fruit.",
    price: 30,
    rate: 4.7,
  },
  {
    id: 6,
    img: require("./images/product6.jpg"),
    title: "Strawberry Shake",
    desc: "Delicious strawberry tasty milkshake.",
    price: 28,
    rate: 4.3,
  },
  {
    id: 7,
    img: require("./images/product7.jpg"),
    title: "Cold Coffee",
    desc: "Chilled coffee with milk and sugar.",
    price: 24,
    rate: 4.1,
  },
  {
    id: 8,
    img: require("./images/product8.jpg"),
    title: "Green Tea",
    desc: "Light and refreshing cold green tea.",
    price: 15,
    rate: 3.8,
  },
  {
    id: 9,
    img: require("./images/product9.jpg"),
    title: "Energy Drink",
    desc: "Boost your energy with this drink.",
    price: 35,
    rate: 4.0,
  },
  {
    id: 10,
    img: require("./images/product10.jpg"),
    title: "Ginger Ale",
    desc: "Spicy and fizzy awesome ginger ale.",
    price: 20,
    rate: 3.7,
  },
  {
    id: 11,
    img: require("./images/product11.jpg"),
    title: "Coconut Water",
    desc: "Hydrating amazing coconut water with very natural tasty electrolytes.",
    price: 25,
    rate: 4.6,
  },
  {
    id: 12,
    img: require("./images/product12.jpg"),
    title: "Vanilla Milkshake",
    desc: "Classic vanilla-flavored beautiful milkshake with tasty flavor.",
    price: 27,
    rate: 4.4,
  },
  {
    id: 13,
    img: require("./images/product13.jpg"),
    title: "Nebula Frost",
    desc: "A cosmic blend of blueberry and mint with a frosty finish with creative mix.",
    price: 32,
    rate: 4.8
},
{
    id: 14,
    img: require("./images/product14.jpg"),
    title: "Crimson Whisper",
    desc: "A mysterious mix of pomegranate, dragon fruit, and a hint of spice it is was adrople.",
    price: 28,
    rate: 4.6
},
{
    id: 15, 
    img: require("./images/product15.jpg"),
    title: "Shadow Mocha",
    desc: "Dark chocolate espresso shake with a smoky caramel twist make you relax.",
    price: 35,
    rate: 4.9
}
];
